### ISSUE TITLE
MOB: Create Wallet. Missing screens and Missing links

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/identity-wallet-mobile#104]
**Missing screens** - TOS - Confirm recovery phrase backup

**Missing links** - `IMPORT EXISTING WALLET` on `Create password` - `COPY PHRASE` on `Backup your wallet` - `FORGOT?` on `Enter password` - `USE DIFFERENT WALLET` on `Enter password`

**Missing text** - `We will confirm on the next screen` on `Backup your wallet`

**Typo Error** [https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/b3aef5cb-9610-41d2-b2c4-de6e913c31f9](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/b3aef5cb-9610-41d2-b2c4-de6e913c31f9)
![typo](https://user-images.githubusercontent.com/47594955/70235949-3e714300-1764-11ea-9d72-abaeeca8266d.png)

Aha! Link: https://kycc.aha.io/features/MOBILE-62

**Comment by CortecKYC** [comment]
As far as I know, IMPORT EXISTING WALLET link is not available because the functionality doesn't exist yet. It's the last bet for Mobile Wallet.

**Comment by CortecKYC** [comment]
@maycon-mello Can you take a look? Should we make this ticket part of the last bet for Mobile Wallet?

**Comment by maycon-mello** [comment]
The missing links and screens are handled in the Backup Wallet bet (current one). I just need to fix the typo issue. 

I`m going to fix it during this bet.

**Comment by maycon-mello** [comment]
This is ready to be tested on build 0.1.7
