### ISSUE TITLE
MOB UI Fix: battery bar

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#106]
On iPhone X and newer - battery/wifi, etc should be displayed with white colours

Aha! Link: https://kycc.aha.io/features/MOBILE-60

**Comment by maycon-mello** [comment]
Fixed on build 0.1.24

**Comment by rhdelima** [comment]
Looks good on my end.

![image](https://user-images.githubusercontent.com/10294014/76405773-9ce13980-63c3-11ea-872c-d23621272beb.png)
