### ISSUE TITLE
MOB UI Fix: buttons

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#107]
- [ ] No letter spacing on buttons - see the style guide
- [ ] Buttons with icons are centred by: Grouping the icon with the text (same spacing always between text and icon) and this group is centred on the button  https://gyazo.com/3e179118ba095cb54ab762058f7077d5

Aha! Link: https://kycc.aha.io/features/MOBILE-59

**Comment by rhdelima** [comment]
@oanamangiurea Can confirm if this is good on your end? See some screenshots below. Thanks!

![image](https://user-images.githubusercontent.com/10294014/80950760-111ae500-8e29-11ea-8a9a-d0e0f0710b23.png)

![image](https://user-images.githubusercontent.com/10294014/80950779-1d06a700-8e29-11ea-9da8-1d3306ae3cb6.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes, looks good now
