### ISSUE TITLE
Terms of Use issues

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/identity-wallet-mobile#114]
**On Android:**
1. TOS should be displayed before Set password screen
2. Some texts are NOT visible/displaying
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/9638f0b2-b1fb-45ea-8955-f804bf9f2e36)

**Comment by CortecKYC** [comment]
@rhdelima Regarding #2: Did you try to scroll down the terms of service? I did it on my phone and I could read the whole document. It would be impossible to fit everything in one screen only.

**Comment by rhdelima** [comment]
@CortecKYC Please see recording of issue 2 - https://drive.google.com/file/d/17EBPeJ-yOMnqb7YDfiX3e_bh6oLqYxty/view?usp=sharing

**Comment by CortecKYC** [comment]
Yes, as discussed during standup with Maycon, the terms of service issue happens on some devices but not on others. I tested on a Samsung with Android 9 and I could scroll down to the end.

**Comment by maycon-mello** [comment]
This is ready for QA.

Can check on this release:
https://play.google.com/apps/test/RQd33H5HZNs/ahAAvZMmjoaaFZkYH7A5OBvlu6xNgxC4FojF6mAGFdJkxzzLZeXmwYSbOaYJ_9WuOVFHzKmX6Ay3YtMVbYYlfoKr7U

**Comment by rhdelima** [comment]
@maycon-mello Opt-in option to tracking is not included on the Terms. Can you confirm if it is intended?

![image](https://user-images.githubusercontent.com/10294014/70992537-e0017880-2104-11ea-9739-e16bef0b3555.png)

**Comment by maycon-mello** [comment]
The crash report & analytics is not implemented yet, so I removed it from the terms. We are going to setup it in a future bet,
