### ISSUE TITLE
MOB5: Send tokens screen

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#119]

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
@maycon-mello Please see some issues below:
1. `MAX` button is not properly aligned
2.  Sending KEY shows ETH on the modal and `Send ETH` button
3. Amount in USD is defaulted to `$1.37 USD`
![image](https://user-images.githubusercontent.com/10294014/72137759-5e7ccd80-33c6-11ea-939d-a46d2ab9e0fa.png)

**Comment by maycon-mello** [comment]
I've fixed the issues.
The update is available on release 0.1.2.

**Comment by rhdelima** [comment]
Looks good. Pass
