### ISSUE TITLE
MOB5: Receive Tokens Screen

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#125]
- [x] Back button
- [x] Header
- [x] Last Price
- [x] Token Contract 
- [x] Handle Ellipsis on token contract
- [x] Receive button
- [x] Send button
- [x] Transactions - Place Holder

**Comment by rhdelima** [comment]
@maycon-mello Failing this one. Please see issues below:
1. Should show token name `SelfKey` beside token icon
2. Token Contract is missing
3. Transaction placeholder is missing

![image](https://user-images.githubusercontent.com/10294014/71333803-7ce56b00-2576-11ea-97f4-59b7c0a36689.png)

**Comment by maycon-mello** [comment]
> @maycon-mello Failing this one. Please see issues below:
> 
> 1. Should show token name `SelfKey` beside token icon
> 2. Token Contract is missing
> 3. Transaction placeholder is missing
> 
> ![image](https://user-images.githubusercontent.com/10294014/71333803-7ce56b00-2576-11ea-97f4-59b7c0a36689.png)

I've fixed these issues, please review again.

**Comment by rhdelima** [comment]
Looks good. Pass
