### ISSUE TITLE
MOB5: Send Tokens - Advanced Options

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#128]
Aha! Link: https://kycc.aha.io/features/MOBILE-88

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
@maycon-mello @oanamangiurea 
The USD value for transaction fee is showing `0.00 USD`. Is it okay to show 3 decimal places to be more accurate?
![image](https://user-images.githubusercontent.com/10294014/72140499-dac5df80-33cb-11ea-8f36-049e3cffb80f.png)

**Comment by CortecKYC** [comment]
@rhdelima I would say no. For FIAT currency only 2 decimals are used.

**Comment by maycon-mello** [comment]
Looking at https://ethgasstation.info/ they are using 3 decimals for the fiat currency, it looks more accurate. Other option is to display 3 decimals only when required, to prevent 0.00 values.

**Comment by CortecKYC** [comment]
Sounds good to me, @maycon-mello

**Comment by maycon-mello** [comment]
This is fixed.
The update is available in release 1.0.2.
Could you kindly test @rhdelima?

**Comment by maycon-mello** [comment]
Thanks, i'm working to fix the issues.

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
Looks good now. Pass
