### ISSUE TITLE
MOB UI Fix: Modals

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#138]
- [ ] Modal backdrop: The opacity layer that is behind a modal should be **rgba(105,124,149,0.9)**. Now it's dark blue. https://gyazo.com/cea623ff10f843b32898bde055a1d5df

- [ ] Modal title: There should be only border bottom on the modal title https://gyazo.com/3aed560d2362bf044e74b182e46b63ee

Aha! Link: https://kycc.aha.io/features/MOBILE-86

**Comment by rhdelima** [comment]
@oanamangiurea Please confirm if you're good with this as well. See sample screenshot below.

![image](https://user-images.githubusercontent.com/10294014/80952184-debeb700-8e2b-11ea-99fb-daee1793e255.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes, looks good
