### ISSUE TITLE
MOB UI Fix: Dashboard

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#139]
- [x] Top center card:

    - decrease top/bottom padding
    - add background gradient
    - fix issue with drop shadow at the bottom - right now it appears you have 2 backgrounds there and no shadow [https://gyazo.com/7271a5c135b86f1b15c253385873a261](https://gyazo.com/7271a5c135b86f1b15c253385873a261)
- [x] My tokens:

    - decrease top/bottom padding of title
    - add background gradient to those cards
    - add drop shadow to card boxes
    - cards should be clickable (touchable) -> they will open the specific token page

Aha! Link: https://kycc.aha.io/features/MOBILE-85

**Comment by rhdelima** [comment]
@oanamangiurea Let us know if you're good with this now. See sample screenshot below.

![image](https://user-images.githubusercontent.com/10294014/81172944-c7b9c980-8fd1-11ea-98f9-073a630d2d5c.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes, all good
