### ISSUE TITLE
MOB UI Fix: token page

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#140]
https://gyazo.com/db7ac91f4389d31d9bd4148460ee56b0

- [ ] Key (token name) and back arrow should be on the same line, vertically centred 
- [ ] Missing token contract address
- [ ] Missing transactions history box

Aha! Link: https://kycc.aha.io/features/MOBILE-84

**Comment by maycon-mello** [comment]
This is fixed.
The update is available on release 1.0.2.

**Comment by rhdelima** [comment]
@maycon-mello Failing this one. Please update ETH page as well. Token contract is missing.

![image](https://user-images.githubusercontent.com/10294014/72276456-e420a780-366a-11ea-9ff2-0debe46efdc1.png)

**Comment by maycon-mello** [comment]
@rhdelima I'm not sure if we should have a token contract for ETH. This field is just valid for ERC-20 tokens like KEY and other custom tokens.
