### ISSUE TITLE
Ethreum abreviation

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#151]
Correct abbreviation for Ethereum is always with uppercase letters: ETH, not eth. 

It should be the same in the entire wallet

 ![IMG_F17A4E17F13A-1.jpeg](https://images.zenhubusercontent.com/5b7beb7f8c0e917986992a6c/f791b76a-0f0e-45d0-a0c2-b871c9924c1b)

**Comment by maycon-mello** [comment]
I've fixed it.
The update is available on release 0.1.2.

**Comment by rhdelima** [comment]
Looks good. Pass
![image](https://user-images.githubusercontent.com/10294014/72273899-298ea600-3666-11ea-834d-e239395caecf.png)
