### ISSUE TITLE
Modal open flow issue

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#152]
When opening some of the modals, the page behind goes back to the previous screen, so when closing the modal the user finds himself on a different page than the one he started from.

EX:  I touch the big SelfKey card at the top, which gets me to the KEY page. If I touch the send button, it will open a modal, while behind the page is now back to dashboard. This is unwanted behaviour. The modal opening should not affect current page.

**Comment by maycon-mello** [comment]
I've fixed it.
The update is available on release 0.1.2.

**Comment by rhdelima** [comment]
Looks good on my end. Pass
