### ISSUE TITLE
Transaction Details modal is missing

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#153]
When clicking in a transaction item the transaction details modal should be displayed.

Expected behavior:

[https://user-images.githubusercontent.com/12645078/72086241-56992c80-32e5-11ea-8601-a199dc7066fd.png](https://user-images.githubusercontent.com/12645078/72086241-56992c80-32e5-11ea-8601-a199dc7066fd.png)

Aha! Link: https://kycc.aha.io/features/MOBILE-83

**Comment by rhdelima** [comment]
@maycon-mello 
I'm unable to test this since after tapping Send button, it only displays blank screen. See recording: https://drive.google.com/file/d/1F45zlHBKbT-_QKdLgBBEMR3ZS4h3n3G3/view?usp=sharing

**Comment by maycon-mello** [comment]
Sorry, ralph. Let me check, I will figure it out and provide a fix.

**Comment by maycon-mello** [comment]
This is ready for QA, Fixed on version 0.1.15

**Comment by rhdelima** [comment]
Looks good. Pass
