### ISSUE TITLE
MOB6: Settings: Backup

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#158]
Aha! Link: https://kycc.aha.io/features/MOBILE-79

**Comment by rhdelima** [comment]
@maycon-mello Please see issues below:
1. Incorrect error message. Should be `Wrong password. Please try again.`
![IMG_5874](https://user-images.githubusercontent.com/10294014/73007549-ad574800-3e47-11ea-8baa-ef3d2956d6b7.PNG)

2. When creating a backup, ios and android have different file type and filename. On IOS, file type is `.sk` while on android is `.zip`. I expect to have the same file type so user can use it on either ios or android. 
![Screenshot_20200124-010212_Drive](https://user-images.githubusercontent.com/10294014/73007693-eee7f300-3e47-11ea-9760-155b9e7a2cc2.jpg)

**Comment by maycon-mello** [comment]
This is ready to be tested on build 0.1.7

**Comment by rhdelima** [comment]
@maycon-mello Can I ask for ios build 0.1.7? Testflight still has the previous version. Thanks!

**Comment by maycon-mello** [comment]
Hi @rhdelima i've fixed it, can you try again please? https://testflight.apple.com/join/qnzHnhHr

**Comment by rhdelima** [comment]
Looks good. Pass
