### ISSUE TITLE
MOB6: Choose Different Wallet

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#159]
Aha! Link: https://kycc.aha.io/features/MOBILE-78

**Comment by rhdelima** [comment]
@oanamangiurea Can you confirm if these issues are valid:
1. Should display error message if wallet is NOT selected after tapping `Unlock`
2. Password error message should be `Wrong password. Please try again.`
![IMG_5874](https://user-images.githubusercontent.com/10294014/73013566-8141c400-3e53-11ea-8e40-856a12c3e122.PNG)

**Comment by oanamangiurea** [comment]
@rhdelima yes, those are valid issues

**Comment by maycon-mello** [comment]
This is ready to be tested on build 0.1.7

**Comment by rhdelima** [comment]
Looks good now. Pass
