### ISSUE TITLE
MOB6: Import backup file

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#161]
Aha! Link: https://kycc.aha.io/features/MOBILE-76

**Comment by maycon-mello** [comment]
This is ready to be tested on build 0.1.7

**Comment by rhdelima** [comment]
@maycon-mello Failing this one. Please see issues below:
1. No field validations. Should display error message if no backup file is selected or password is incorrect
2. Nothing happens after selecting backup file with correct password

**Comment by maycon-mello** [comment]
Hi @rhdelima, is that for Android or iOS?

**Comment by rhdelima** [comment]
@maycon-mello Issue 1 is also encountered on iOS. Also, if I import backup on iOS, I can't select the backup file in zip format. 
https://monosnap.com/file/gBSNaeaIJdzpE9p22UdPX3Z82GVWk7

**Comment by rhdelima** [comment]
Looks good. Pass
