### ISSUE TITLE
Wallet crashes when tapping Send on KEY/ETH modal using IOS

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/identity-wallet-mobile#166]
**Steps to replicate:**
1. Create or unlock mobile wallet
2. On dashboard, tap Send/Receive icon on KEY or ETH widget
3. Tap on Send button

**Expected Result:**
Send Modal is opened

**Actual Result:**
App crashes.

**Comment by maycon-mello** [comment]
It seems to be an issues related to an old build, the build 0.1.2 looks good.

**Comment by CortecKYC** [comment]
@rhdelima Which build did you test?

**Comment by maycon-mello** [comment]
@rhdelima confirmed that it is working fine on the current build 0.1.2. I've also expired old builds to avoid other issues.
