### ISSUE TITLE
NAN is showing on KEY using iOS

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/identity-wallet-mobile#167]
[https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/96b44100-434a-4904-b215-6e5a0da39bd2](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/96b44100-434a-4904-b215-6e5a0da39bd2)

Aha! Link: https://kycc.aha.io/features/MOBILE-73

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
Looks good now. Pass
