### ISSUE TITLE
Duplicate word on recovery phrase

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/identity-wallet-mobile#187]
[https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/ed92624d-eb40-4572-b2db-868304714895](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/ed92624d-eb40-4572-b2db-868304714895)

Aha! Link: https://kycc.aha.io/features/MOBILE-125

**Comment by maycon-mello** [comment]
This is ready for QA. Build 0.1.17

**Comment by rhdelima** [comment]
I haven't encountered duplicate word on recovery phrase again.

**Comment by CortecKYC** [comment]
@rhdelima Can we consider it passed?

**Comment by rhdelima** [comment]
@CortecKYC nope. As per Maycon, it is normal to have duplicates on recovery phrase and this was not handled properly before. So when user confirmed recovery phrase and selecting any of the duplicates, the other disappeared as well.

**Comment by CortecKYC** [comment]
Ok, I understand. But this shouldn't be a blocker for release.

**Comment by rhdelima** [comment]
Yes. Not a blocker

**Comment by maycon-mello** [comment]
On my understanding it can be closed, I already updated the implementation to handle duplicates on the recovery phrase.
