### ISSUE TITLE
MOB7: Screen: Import Steps

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#190]
[https://projects.invisionapp.com/d/main?origin=v7?origin=v7?origin=v7#/console/18106826/379636423/history](https://projects.invisionapp.com/d/main?origin=v7?origin=v7?origin=v7#/console/18106826/379636423/history)

Aha! Link: https://kycc.aha.io/features/MOBILE-124

**Comment by rhdelima** [comment]
Looks good. Pass
