### ISSUE TITLE
MOB7: Screen: Read QR Code from desktop

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#191]
[https://projects.invisionapp.com/d/main?origin=v7?origin=v7?origin=v7#/console/18106826/379636422/history](https://projects.invisionapp.com/d/main?origin=v7?origin=v7?origin=v7#/console/18106826/379636422/history)

Aha! Link: https://kycc.aha.io/features/MOBILE-123

**Comment by CortecKYC** [comment]
@rhdelima Are you still testing this one?

**Comment by maycon-mello** [comment]
Max improved the desktop wallet to generate a QR Code with less data, I will have to update the mobile wallet to read this properly.

**Comment by maycon-mello** [comment]
This is ready for QA on build 0.2.3

**Comment by rhdelima** [comment]
Looks good. Pass
