### ISSUE TITLE
MOB7: Screen: Password to import

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#192]
[https://projects.invisionapp.com/d/main?origin=v7?origin=v7?origin=v7#/console/18106826/379636424/history](https://projects.invisionapp.com/d/main?origin=v7?origin=v7?origin=v7#/console/18106826/379636424/history)

Aha! Link: https://kycc.aha.io/features/MOBILE-122

**Comment by rhdelima** [comment]
@maycon-mello Failing this one. Please see issues below:
1. Update field label to `PASSWORD` only
2. Update error message for incorrect password

![image](https://user-images.githubusercontent.com/10294014/76969820-e56d9980-6965-11ea-9a15-c20b7b25ee78.png)

**Comment by CortecKYC** [comment]
@maycon-mello Please fix

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
Looks good. Pass
