### ISSUE TITLE
MOB7: Manage tokens: List

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#198]
https://projects.invisionapp.com/d/main?origin=v7?origin=v7?origin=v7#/console/18106826/376410313/history

What to test:

- Manage Tokens link from dashboard
- Empty tokens message on Manage tokens screen
- Mange tokens link from navigation menu

The token list is already developed, however you can't add tokens yet. I'm working on the add tokens functionality in a separate issue, then it can be tested there.

**Comment by rhdelima** [comment]
Looks good. But I suggest to fix the first quotation mark to opening quotation mark. 
@oanamangiurea Please confirm.

![image](https://user-images.githubusercontent.com/10294014/73928472-1a6de180-490e-11ea-87e7-92b970011da1.png)

**Comment by oanamangiurea** [comment]
@rhdelima good catch, yes that should be fixed. I also just fixed it in invision

**Comment by maycon-mello** [comment]
This is ready for QA, Fixed on build version 0.1.15

**Comment by rhdelima** [comment]
Looks good. Pass
