### ISSUE TITLE
MOB7: Manage tokens: Create and delete

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#199]
Aha! Link: https://kycc.aha.io/features/MOBILE-116

**Comment by maycon-mello** [comment]
This is ready for QA, Fixed on version 0.1.15

**Comment by rhdelima** [comment]
@maycon-mello Please see issues below:
1. Incorrect icon for hide. Should be eye + slash icon
![image](https://user-images.githubusercontent.com/10294014/74504933-c4fa8b80-4f30-11ea-96c1-2d5e54813f0e.png)
2. Missing check icon when address is valid
![image](https://user-images.githubusercontent.com/10294014/74505196-7b5e7080-4f31-11ea-8b66-e7d2bdfa21ab.png)
3. Error and search messages should not be displayed at the same time
![image](https://user-images.githubusercontent.com/10294014/74505276-b365b380-4f31-11ea-92ad-476ff9f3ac44.png)
4. Most of the ERC20 tokens like AXP, USDT etc were not accepted.

**Comment by maycon-mello** [comment]
This is ready for QA. Build 0.1.17

**Comment by rhdelima** [comment]
@maycon-mello Please see more issues below:
1. Tokens are still shown even after hiding them https://monosnap.com/file/QX8thiF58Ia7tSkYvMpELnL7ZV52Tp
2. Incorrect error message for invalid tokens. Should be `Token contract does not exist or not supported. Please double check and try again.`
![IMG_6428](https://user-images.githubusercontent.com/10294014/74815996-3a050100-5335-11ea-95ab-53e4f90bcd83.PNG)
3. Can add duplicate tokens. Should display error `Address is already being used.` when token already exists
![IMG_6429](https://user-images.githubusercontent.com/10294014/74816066-5c971a00-5335-11ea-8647-1c58cf724295.PNG)
4. ETH and KEY are no longer displayed after adding tokens
![IMG_6430](https://user-images.githubusercontent.com/10294014/74816455-2908bf80-5336-11ea-8a4b-3a53d8b8183e.PNG)

**Comment by rhdelima** [comment]
@maycon-mello Additional issue on android:
1. Address added is not displayed after search is completed.
![image](https://user-images.githubusercontent.com/10294014/74874332-c1855b00-539b-11ea-8057-76946f33ccae.png)

**Comment by maycon-mello** [comment]
I've fixed the issue. This is ready for QA on build 0.1.19.

**Comment by rhdelima** [comment]
@maycon-mello All other issues are fixed except Address not displayed after found on android. Should we log a separate issue for it?

**Comment by CortecKYC** [comment]
@rhdelima Yes, please. If all other issues are fixed, pass this ticket and log a new ticket with the single issue that remains.

**Comment by rhdelima** [comment]
got it. Logged https://github.com/SelfKeyFoundation/identity-wallet-mobile/issues/239 for the remaining issue
