### ISSUE TITLE
Confirm Mnemonic Screen: improve the behavior of "Clear" button 

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#200]
Current Behvior
- When user clicks on 'Clear', then all the words are removed.

Expected behavior:
- When user clicks on 'Clear', then remove only the last word

**Comment by maycon-mello** [comment]
This is ready for QA. Build 0.1.17

**Comment by rhdelima** [comment]
Looks good. Pass
