### ISSUE TITLE
User should be able to send custom tokens

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#208]
Aha! Link: https://kycc.aha.io/features/MOBILE-115

**Comment by maycon-mello** [comment]
This is ready for QA. Build 0.1.17

**Comment by rhdelima** [comment]
@maycon-mello Please see issues below:
1. KEY should also be available on Token drop down
2. Can we add more decimal places on the USD value to be more accurate?
![image](https://user-images.githubusercontent.com/10294014/74823902-72f7a280-5342-11ea-8c06-f418109d109a.png)

**Comment by rhdelima** [comment]
@maycon-mello Please see additional issue:
3. Should only display token with balance. 

@oanamangiurea  ,
Can you confirm? This is the behavior we have on desktop wallet

**Comment by oanamangiurea** [comment]
@rhdelima I would display all tokens, it's hard for the user to figure his balance needs to be more than 0, maybe he came straight to this place before checking.

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
Looks good. Pass
