### ISSUE TITLE
MOB: Import a wallet with seed phrase

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#211]
UI improvements to make it easier to setup a wallet by using the seed phrase

Aha! Link: https://kycc.aha.io/features/MOBILE-114

**Comment by rhdelima** [comment]
@maycon-mello Testing is blocked by https://github.com/SelfKeyFoundation/identity-wallet-mobile/issues/329

**Comment by rhdelima** [comment]
Looks good. Pass
