### ISSUE TITLE
MOB: Settings page

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#214]
MOB: Settings page

1. I think privacy policy should be a text contained in the app, not open a website, which is not normal behaviour to be found by a link in settings. We can display it in a modal like we have Terms & Conditions. Plus the text of privacy policy should be made custom to the app itself.
2. Backup page: display a back arrow at he top of the left corner, remove the back button, update header text [https://projects.invisionapp.com/d/main#/console/18106826/405387030/preview](https://projects.invisionapp.com/d/main#/console/18106826/405387030/preview)
3. Recovery information should first ask for password [https://projects.invisionapp.com/d/main#/console/18106826/405388050/preview](https://projects.invisionapp.com/d/main#/console/18106826/405388050/preview) , then display recovery phrase [https://projects.invisionapp.com/d/main#/console/18106826/405388110/preview#project\_console](https://projects.invisionapp.com/d/main#/console/18106826/405388110/preview#project_console)

Aha! Link: https://kycc.aha.io/features/MOBILE-113

**Comment by maycon-mello** [comment]
This is ready for QA. Build 0.2.4

**Comment by rhdelima** [comment]
@maycon-mello  Failing this one. I also added some issues related to the screens on this ticket.

**Privacy Policy**
- Not sure if statement is custom made for the mobile app. Please confirm
![image](https://user-images.githubusercontent.com/10294014/78543100-b9d62480-782a-11ea-8c97-d06e688215ab.png)


**Backup screen**
- Header text not fixed
- Update `Enter Password` to `Password`
- Missing eye icon on Password field
- Missing Forgot link
![image](https://user-images.githubusercontent.com/10294014/78539851-d02db180-7825-11ea-9f99-e5f3ada79eed.png)

**Password for Recovery Information screen**
- Incorrect header text
- Update `Enter Password` to `Password`
- Missing eye icon
- Missing Forgot link
- Replace buttons
![image](https://user-images.githubusercontent.com/10294014/78541125-b7be9680-7827-11ea-9c5a-bc3436197f45.png)

**Recovery Information screen**
- Missing back arrow
- Incorrect header text
- Remove button
![image](https://user-images.githubusercontent.com/10294014/78542596-fa816e00-7829-11ea-80ed-5237d5ed1709.png)

**Comment by rhdelima** [comment]
@maycon-mello Please update header text to `Recover your wallet`

![image](https://user-images.githubusercontent.com/10294014/79741584-19a4f300-8334-11ea-8a4b-a2f7f1f80d9e.png)

**Comment by rhdelima** [comment]
Looks good now. Pass
