### ISSUE TITLE
Missing Token details page for ERC-20 tokens

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#217]
Like for KEY and ETH, if a user taps on any token from the "My Tokens" list we should show a view with the Token Details page . See this screen [https://projects.invisionapp.com/d/main#/console/18106826/376936812/preview](https://projects.invisionapp.com/d/main#/console/18106826/376936812/preview)

Aha! Link: https://kycc.aha.io/features/MOBILE-111

**Comment by maycon-mello** [comment]
This is ready for QA on build 0.1.19

**Comment by rhdelima** [comment]
Looks good. Pass
