### ISSUE TITLE
Settings: Nothing happens when clicking "Change Passcode" and "Recovery Information" 

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/identity-wallet-mobile#218]
Android 10  
Google Pixel 3
Reported by: Charlie
When I navigate to settings and click "Change Passcode" or "Recovery Information" nothing happens

Aha! Link: https://kycc.aha.io/features/MOBILE-110

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
Looks good. Pass
