### ISSUE TITLE
Wrong behaviour for hiding tokens

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#219]
The desired behavior for hiding tokens when users swipes left is that the box stops and the user can press on hide. Similar to a mail app, where on swipe you have controls like Mark as read. 

Right now users has to dismiss the row and that is not intuitive.

Aha! Link: https://kycc.aha.io/features/MOBILE-109

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
Looks good. Pass

**Comment by oanamangiurea** [comment]
Reopening this, as it still has issue. 

After swiping left, if I want my list to return to "normal" state I have to swipe the token back to the right. 

**Desired behavior:** 

1. Tapping on that item or outside of it, except for the hide button should return the item to "normal" state 
2. Also, the page should not scroll while I swipe in the token list. 
Example: see any mail app, or this react native implementation here https://snack.expo.io/@jemise111/react-native-swipe-list-view 

PS: we can definitely launch without this being fixed

**Comment by CortecKYC** [comment]
**Not a blocker for release**

**Comment by maycon-mello** [comment]
Fixed on build 0.1.24

**Comment by rhdelima** [comment]
This looks good on my end. @oanamangiurea Let me know if this works on your end too.

https://monosnap.com/file/0snSzFsendtK9Nda2Xdlu3Ve6k0TbE

**Comment by oanamangiurea** [comment]
@rhdelima yes, all good now
