### ISSUE TITLE
Double transaction

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/identity-wallet-mobile#220]
Android 10
Reported by Joonas
I somehow managed to double-tap the send button and the transaction was sent two times

![doubletap.png](https://images.zenhubusercontent.com/5c6a709f9d62b128eab3a3a5/e140dd96-43aa-46bb-9b16-71d4f03c49b2)

Aha! Link: https://kycc.aha.io/features/MOBILE-108

**Comment by CortecKYC** [comment]
@maycon-mello Please add an estimation for this ticket

**Comment by maycon-mello** [comment]
I've fixed the issue. This is ready for QA on build 0.1.19.

**Comment by rhdelima** [comment]
Looks good. Pass
