### ISSUE TITLE
Successful transaction in etherscan not showing in Mobile Wallet

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/identity-wallet-mobile#221]
Android 9
Samsung Galaxy J5
Reported by Susana

I sent ETH to the new mobile wallet I created and while the transaction shows as successful in etherscan, the ETH hasn't arrived to the wallet
( I have double-checked that everything was correct and it seems so) 
I tried closing and opening the wallet but nothing
Is it normal that it would take that long?
https://etherscan.io/tx/0xf449aff091daf9c49f036c7c617ab393a157543f0d8c82f5b2c1d17362809f19

Aha! Link: https://kycc.aha.io/features/MOBILE-106

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
Looks good on my end. Pass
