### ISSUE TITLE
Slow loading when entering the password

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/identity-wallet-mobile#222]
Android 9
Samsung Galaxy J5
Reported by Susana

It gets stuck sometimes when entering the password, it loads for a long time until you get to access

Aha! Link: https://kycc.aha.io/features/MOBILE-105

**Comment by maycon-mello** [comment]
I've fixed the issue. This is ready for QA on build 0.1.19.

**Comment by rhdelima** [comment]
Looks good on my end. Pass
