### ISSUE TITLE
My tokens: can't scroll down to see whole list

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/identity-wallet-mobile#223]
Android 9
Samsung Galaxy J3
Reported by Cristina

I have added several tokens but in the "Manage Tokens/My tokens" tab I can't scroll down to see the whole list. Only the first ones show up.  
**Note:** It only happens in "my tokens. It works fine in the dashboard 

![Screenshot_20200217-125927_SelfKey.jpg](https://images.zenhubusercontent.com/5c6a709f9d62b128eab3a3a5/cf9e5e41-68d9-4c1e-bfe1-56a1864089c1)

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
Looks good on my end. @CortecKYC Can we close this one? Does it looks good on your end as well?
