### ISSUE TITLE
Camera stays on in the background after scanning QR code

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/identity-wallet-mobile#224]
Android 10 and iOS
Reported by Joonas, Gabriel, Deepak

Aha! Link: https://kycc.aha.io/features/MOBILE-107

**Comment by maycon-mello** [comment]
I've fixed the issue. This is ready for QA on build 0.1.19.

**Comment by rhdelima** [comment]
Looks good. Pass
