### ISSUE TITLE
Login screen pops up randomly and asks again to enter password

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/identity-wallet-mobile#226]
Android (OnePlus 7)
Reported by Deepak
Sometimes while logging in entered password to unlock but it pops out again the login screen and asks again to enter the password

Aha! Link: https://kycc.aha.io/features/MOBILE-103

**Comment by maycon-mello** [comment]
I'm no longer able to reproduce the issue, it seems to be working fine. Can you please check ralph?

**Comment by rhdelima** [comment]
Looks good on my end as well.
