### ISSUE TITLE
Issues with ETH transactions

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/identity-wallet-mobile#229]
iOS - Iphone x
Reported by Gabriel
- Sent myself test ETH but had to log out and back in to see it – amounts do not auto-refresh
- ETH send – shows as pending, but when you click on transaction it says complete, when you check on etherscan, it says failed – due to gas
- 2nd send transaction failed – put gas at fast, still failed

Aha! Link: https://kycc.aha.io/features/MOBILE-100

**Comment by maycon-mello** [comment]
I've fixed the issue. This is ready for QA on build 0.1.19.
