### ISSUE TITLE
Scan QR option within the address field not responsive when sending ETH

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/identity-wallet-mobile#230]
iOS - Iphone x
Reported by Gabriel

The scan QR option within the address field is not responsive when sending ETH

Aha! Link: https://kycc.aha.io/features/MOBILE-99

**Comment by maycon-mello** [comment]
Hi @rhdelima, I'm not able to reproduce the issue on iphone XR. I'm wondering if this specific for iphone X, can you please check?

**Comment by rhdelima** [comment]
Looks good on my end as well. I think the issue was encountered using previous builds.
