### ISSUE TITLE
Display shorter Keyboard

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#231]
We don't need keyword with predictability feature on iOS, can we use the shorter version instead?

[https://gyazo.com/191026f06fbc1cf813ef8df247b235cc](https://gyazo.com/191026f06fbc1cf813ef8df247b235cc)

Aha! Link: https://kycc.aha.io/features/MOBILE-98

**Comment by rhdelima** [comment]
Looks good. Pass
