### ISSUE TITLE
MOB: Improve login for multiple wallet address

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#234]
Users with more than a wallet address have to click more to be able to login. As discussed during standup we want the following behavior:

If the user has only one address, keep everything as it is

If the user has more than one address, then when they open the wallet they should see straight this screen https://projects.invisionapp.com/d/main#/console/18106826/405784582/preview where we pre select in the dropdown the last address they used

Aha! Link: https://kycc.aha.io/features/MOBILE-95

**Comment by rhdelima** [comment]
@maycon-mello Failing this one. Should pre-select last address used. See recording: https://monosnap.com/file/JUs5CIPQQjnMq0hu5Z1zHK3LBZ2Bd0

**Comment by oanamangiurea** [comment]
@rhdelima good point you made. @maycon-mello I added on that screen under the button a link to create new wallet https://projects.invisionapp.com/d/main#/console/18106826/405784582/preview. which should direct to this screen https://projects.invisionapp.com/d/main#/console/18106826/380320249/preview#project_console in case the user wants to import it from desktop

**Comment by maycon-mello** [comment]
Thank you, I will work on this changes.

**Comment by rhdelima** [comment]
Looks good now. Pass
