### ISSUE TITLE
Display correct error message if wallet is already existed

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/identity-wallet-mobile#246]
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/d7451f3d-98e6-40a0-a8c2-dab51aaf7b87)

Aha! Link: https://kycc.aha.io/features/MOBILE-132

**Comment by CortecKYC** [comment]
@maycon-mello What's the status of this ticket?

**Comment by maycon-mello** [comment]
I've already fixed it along with export wallet implementation, moving it to QA Rady.

**Comment by maycon-mello** [comment]
I've found a small issue on it, it needs to be deployed again.

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
Failing this one.
1. No error is shown when importing existing backup file
2. Incorrect password is displayed when importing same wallet from desktop

**Comment by maycon-mello** [comment]
Thanks for testing Ralph.
I've fixed the issues mentioned, this is ready for QA on build 0.2.3

**Comment by rhdelima** [comment]
Looks good. Pass
