### ISSUE TITLE
MOB: Token Detail Name

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#249]
In The Token Detail modal, for ERC-20 tokens we are missing the actual full token name, as it is in design:

https://projects.invisionapp.com/d/main#/console/18106826/376936812/preview 

See that the name of the page is the Token Abbreviation REP, but we also display the full token name Augur. This is very important as there are tokens out there with similar abbreviation, KEY is one of them.  

https://gyazo.com/8b59c70fefc526429868e3c77c9818d5

Aha! Link: https://kycc.aha.io/features/MOBILE-129

**Comment by rhdelima** [comment]
Can we include this one as well? Should display token name.

![image](https://user-images.githubusercontent.com/10294014/75333668-81edd000-58c1-11ea-8a05-5dbbb97adc15.png)

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/75425061-eae64e00-597c-11ea-8071-8ade934701ac.png)
![image](https://user-images.githubusercontent.com/10294014/75425087-f76aa680-597c-11ea-939a-ff603af86523.png)
