### ISSUE TITLE
Back button is not responsive on Import Wallet from backup file

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/identity-wallet-mobile#250]
Device: iphoneX

[https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/29d036be-0ad0-4ca5-b8c9-9cdffce94239](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/29d036be-0ad0-4ca5-b8c9-9cdffce94239)

Aha! Link: https://kycc.aha.io/features/MOBILE-128

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
Looks good. Pass
