### ISSUE TITLE
Icon box sizes are not consistent

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/identity-wallet-mobile#251]
[https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/3f2e09b2-7397-4ffc-b016-71d591480a1e](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/3f2e09b2-7397-4ffc-b016-71d591480a1e)

Aha! Link: https://kycc.aha.io/features/MOBILE-127

**Comment by maycon-mello** [comment]
Fixed on build 0.1.24

**Comment by rhdelima** [comment]
Looks good. Pass
