### ISSUE TITLE
MOB UI Fix: Button UI Change for accesibility

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#258]
For better contrast we. need to change the text color on the blue button - Full Primary from white to UI-Base-Dark #1E262E

The button should be updated everywhere, hope it's a theme thing and you only need to update it in one place. Stylguide updated with the change https://projects.invisionapp.com/d/main#/console/18338704/380909873/preview 
and updating all InVision screens as well - it will look like this in the app https://gyazo.com/974d0226f42a9cb99dce2ac559918abc

Aha! Link: https://kycc.aha.io/features/MOBILE-156

**Comment by rhdelima** [comment]
@oanamangiurea Please confirm if you're good with the fix. See sample screenshots below:

![image](https://user-images.githubusercontent.com/10294014/80698178-ac037e80-8b0c-11ea-9554-04dff6f93573.png) 
![image](https://user-images.githubusercontent.com/10294014/80698591-4794ef00-8b0d-11ea-8e9c-e51ba6f116b5.png)

**Comment by oanamangiurea** [comment]
@rhdelima looks good, pass
