### ISSUE TITLE
MOBAnalytics: Events: Create Wallet

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#265]
Aha! Link: https://kycc.aha.io/features/MOBILE-152

**Comment by maycon-mello** [comment]
This is ready for QA on build 0.2.6.

**Comment by rhdelima** [comment]
@maycon-mello Failing this one. An event Create Wallet should be created after setupComplete.

![image](https://user-images.githubusercontent.com/10294014/78972717-f5c9fc00-7b40-11ea-83d9-e75ab03af91f.png)

**Comment by rhdelima** [comment]
@maycon-mello It works on ios but not on android.
https://analytics.selfkey.org/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday&updated=6#?idSite=3&period=day&date=2019-05-10&category=Dashboard_Dashboard&subcategory=1&popover=visitorProfile$3Af00eb0067894aae4
![image](https://user-images.githubusercontent.com/10294014/79312121-03142b80-7f31-11ea-8e88-ee7f05f9e271.png)

**Comment by rhdelima** [comment]
Looks good now. pass
