### ISSUE TITLE
MOBAnalytics: Events: Unlock Wallet

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#267]
Aha! Link: https://kycc.aha.io/features/MOBILE-150

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
@maycon-mello Failing this one. Event unlock is not tracked on iphone X

![image](https://user-images.githubusercontent.com/10294014/78656428-f755b300-78f9-11ea-8e3d-590d4ea763ac.png)

**Comment by maycon-mello** [comment]
Thanks for testing Ralph.
I've fixed these issues on build 0.2.6. Can you please check again?

**Comment by rhdelima** [comment]
@maycon-mello Failing this one. Duplicate events are created for newly created wallet. Please follow steps below:
1. Create a new wallet
2. Close app
3. Open app
4. Unlock wallet
5. Check matomo

![image](https://user-images.githubusercontent.com/10294014/78974776-522f1a80-7b45-11ea-9061-3cb19e6d3f51.png)

**Comment by rhdelima** [comment]
Looks good. Pass
