### ISSUE TITLE
MOBAnalytics: Events: Send Tokens

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#269]
Aha! Link: https://kycc.aha.io/features/MOBILE-148

**Comment by rhdelima** [comment]
@maycon-mello Please fix undefined when opening Send from Custom Tokens screen
![image](https://user-images.githubusercontent.com/10294014/79332125-d4a54900-7f4e-11ea-9598-e1b80086c70b.png)
