### ISSUE TITLE
MOBAnalytics: Events: Token Details

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#271]
Aha! Link: https://kycc.aha.io/features/MOBILE-146

**Comment by maycon-mello** [comment]
This is ready for QA.

**Comment by rhdelima** [comment]
@maycon-mello Failing this one. `app://app/tokenDetails` should be an event. Also, can we add what token is visited here?

![image](https://user-images.githubusercontent.com/10294014/78976409-aee00480-7b48-11ea-85f6-00c78156f785.png)

**Comment by maycon-mello** [comment]
Hi @rhdelima, app://app/tokenDetails is a page view right now. Yes I can add the token visited
