### ISSUE TITLE
MOBAnalytics - Events: Manage Tokens

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#273]
Aha! Link: https://kycc.aha.io/features/MOBILE-144

**Comment by maycon-mello** [comment]
This is ready for QA on build 0.2.6.

**Comment by rhdelima** [comment]
@maycon-mello Failing this one too. No event create when tapping on Manage in the dashboard.

![image](https://user-images.githubusercontent.com/10294014/78975584-f6fe2780-7b46-11ea-87cb-88db869862a4.png)
