### ISSUE TITLE
MobBiometrics: Unlock with FaceID

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#317]

**Comment by rhdelima** [comment]
@maycon-mello Please see some issues below:
1. When FaceID fails (not recognized) or clicks on cancel, Password incorrect is shown
2. If attempts reached the limit and user tries to use FaceID, nothing happens. I think it's better to show message to try again later or use password instead. What do you think @oanamangiurea ?
https://drive.google.com/file/d/1Gi8Fui3NA4HWXicGYrH47kKiBqYLt06b/view?usp=sharing

**Comment by oanamangiurea** [comment]
@rhdelima @maycon-mello for 2nd point raised by Ralph, indeed it should show to try passcode option instead, in the same modal open by face id -> so like this, but for faceid [![Screenshot from Gyazo](https://gyazo.com/30d11a387b87f7df319b85a42a3050fc/raw)](https://gyazo.com/30d11a387b87f7df319b85a42a3050fc)

**Comment by rhdelima** [comment]
Looks good. Pass
