### ISSUE TITLE
MobBiometrics: Unlock with Fingerprint

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#319]

**Comment by rhdelima** [comment]
@maycon-mello Please see issue below:
1. When clicking on Cancel button or attempts limit is reached, Unlock via Fingerprint button shows loading icon (nonstop) and Unlock via Password is missing label
https://drive.google.com/file/d/1dVOFvixDaRPVzCQrfq1yZp1xhTbcHHQA/view?usp=sharing

**Comment by rhdelima** [comment]
Looks good. Pass
