### ISSUE TITLE
MobBiometrics: Analytics

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#321]

**Comment by rhdelima** [comment]
@maycon-mello Failing this one. Enabling fingerprint or faceid ON is always set to false in matomo.

![image](https://user-images.githubusercontent.com/10294014/86205998-f00f1000-bb9d-11ea-9f6d-f384babd6459.png)

**Comment by rhdelima** [comment]
Looks good. pass
