### ISSUE TITLE
Edit Information modal

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/identity-wallet-mobile#327]
The edit profile information modal should follow the ones we have on the desktop, using same naming conventions 

https://gyazo.com/b6b7bca0a99470b56289b90ae16409f2 vs https://gyazo.com/d07cdedc99d682d980148e96a72dc86c

1. The modal title should be Edit Information
2. Attribute input becomes Type, and it's disabled (use disable styling from UI guide)

**Comment by rhdelima** [comment]
Looks good. Pass
