### ISSUE TITLE
Wallet setup complete after skipping or enabling fingerprint or faceid

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/identity-wallet-mobile#329]
It skips verifying the seed phrase. 

https://drive.google.com/file/d/1fikgySmJebTk3zm3FBU-tIFqDEkwA8J9/view?usp=sharing

**Comment by rhdelima** [comment]
@maycon-mello Issue still exists. I suggest to show enable fingerprint/faceid/touchid after wallet setup.

**Comment by maycon-mello** [comment]
Sure, showing after setup complete seems better. I will change the flow. Thanks Ralph!

**Comment by maycon-mello** [comment]
The updates are ready for testing @rhdelima

**Comment by rhdelima** [comment]
Looks good now. Pass
