### ISSUE TITLE
When biometric is OFF, incorrect button is shown on Backup wallet screen

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/identity-wallet-mobile#330]
1. Button is incorrect
2. When clicking button, it opens fingerprint/faceid unlock.

https://drive.google.com/file/d/1isZJOEyIIomj8LXJ2mjokGi4RrGOhXwO/view?usp=sharing

**Comment by maycon-mello** [comment]
This is ready for QA

**Comment by rhdelima** [comment]
@maycon-mello still failed. Button should be `Create Backup`

![image](https://user-images.githubusercontent.com/10294014/86906811-ac407b80-c146-11ea-9e46-87af38b8640d.png)

**Comment by maycon-mello** [comment]
I've fixed the issue, thanks @rhdelima

**Comment by rhdelima** [comment]
Looks good. Pass
