### ISSUE TITLE
MOBProfile: Add Attribute

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#339]

**Comment by rhdelima** [comment]
@maycon-mello please see issues below:
1. When adding date of birth, calendar is not showing
![image](https://user-images.githubusercontent.com/10294014/90089343-bd873400-dd53-11ea-9a04-a74be3b98438.png)
2. When adding a country field, placeholder is showing `Select a Token`
![image](https://user-images.githubusercontent.com/10294014/90089390-e0194d00-dd53-11ea-90a8-378b3284253f.png)
3. Some placeholders are truncated
![image](https://user-images.githubusercontent.com/10294014/90089435-fa532b00-dd53-11ea-996e-981ecc54cae9.png)

**Comment by rhdelima** [comment]
@maycon-mello Please see remaining issues below:
1. When adding content, keypad closes after entering a character.
https://drive.google.com/file/d/1750GhSz8SY7JwEi_ur-tbdaEt0XlAk-j/view?usp=sharing
2. Missing fields on android for address
![image](https://user-images.githubusercontent.com/10294014/90632743-7a4b2a80-e257-11ea-9f5e-46405504d3fc.png)

**Comment by rhdelima** [comment]
Testing is in progress

**Comment by rhdelima** [comment]
@maycon-mello Issue below is not fixed yet.
1. Missing fields on android for address
![image](https://user-images.githubusercontent.com/10294014/90632743-7a4b2a80-e257-11ea-9f5e-46405504d3fc.png)

**Comment by maycon-mello** [comment]
I was able to fix it, can you please check again @rhdelima .

**Comment by rhdelima** [comment]
Looks good now. Pass
