### ISSUE TITLE
MOBProfile: List document

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#341]

**Comment by rhdelima** [comment]
@maycon-mello Failing this one due to:
1. Unable to preview images/pdf for multiple uploads
2. Unable to preview file on edit information modal
3. Some documents are not displaying after saving

**Comment by rhdelima** [comment]
Testing is in progress

**Comment by rhdelima** [comment]
Looks good.Pass
