### ISSUE TITLE
MOBProfile: Add document

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#342]

**Comment by rhdelima** [comment]
@maycon-mello Please see issues below.
1. No validation message for Label if left blank and no file is uploaded
2. Bank Statement, Passport, Tax Cert, CV, Professional Letter are not saved/displayed after saving https://drive.google.com/file/d/1C1QBFLoPEt31TBCxkOSy-4vFxqcSo6aC/view?usp=sharing
3. Driver's License National ID, etc shows 1 file though 3 images are uploaded
4. Voice ID, External Document, CV modals are showing an attachment even no file is uploaded yet
![image](https://user-images.githubusercontent.com/10294014/90764445-e6db2d80-e31a-11ea-96bf-4fb787b399e6.png)
5. Wallet crashes when selecting file for Voice ID. (already sent a report)
6. Unable to upload file for External Document

**Comment by rhdelima** [comment]
Testing is in progress

**Comment by rhdelima** [comment]
Looks good. Pass
