### ISSUE TITLE
Profile Tab for DID

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#352]

**Comment by maycon-mello** [comment]
This is ready for QA.

**Comment by rhdelima** [comment]
@maycon-mello Please see issues below:
1. Update typo errors
2. Can we remove No DID?

![image](https://user-images.githubusercontent.com/10294014/93207785-10f30480-f78e-11ea-9228-44e8b5a99008.png)
