### ISSUE TITLE
KeyFi Marketplace

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#357]

**Comment by rhdelima** [comment]
@maycon-mello See issues below:
1. Date field shows a different calendar. https://prnt.sc/vldywx
2. Middle Name should not be required https://prnt.sc/vle128
3. Typo errors https://prnt.sc/vle33e
4. IOS: App crashes when clicking Add New on SK Profile

**Comment by andregoncalves** [comment]
@maycon-mello what's the status of this?

**Comment by maycon-mello** [comment]
This should be closed
