### ISSUE TITLE
Mobile Release 0.4.16

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#379]

**Comment by rhdelima** [comment]
@maycon-mello Testing is still in progress. But please fix the issue below:
1. App crashes when scanning QR https://take.ms/GitcH
Also, can you confirm what fixes/new features (if any) are included on this build?

**Comment by maycon-mello** [comment]
This is ready for testing

**Comment by rhdelima** [comment]
@maycon-mello Please fix the following:

1. Incorrect transaction fee.
![image](https://user-images.githubusercontent.com/10294014/104296148-44eff380-54fc-11eb-97cf-847f76a6b0c7.png)

2. Unlock button is not working on android.
3. Unable to upload profile photo

**Comment by maycon-mello** [comment]
This is ready for testing. Build 0.4.16 (2)

**Comment by rhdelima** [comment]
@maycon-mello The other two issues are still NOT fixed.

- Unlock button is not working on android.
- Unable to upload profile photo

**Comment by maycon-mello** [comment]
Thanks, I will check those
