### ISSUE TITLE
Screen: Setup Complete

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#64]
- [x] Create screen
- [x] Create storybook stories

https://projects.invisionapp.com/d/main?origin=v7?origin=v7?origin=v7#/console/18106826/379025057/preview

![image](https://user-images.githubusercontent.com/12645078/66387167-ccfe5980-e999-11e9-99cb-a379417141c7.png)

Aha! Link: https://kycc.aha.io/features/MOBILE-49

**Comment by rhdelima** [comment]
Looks good. Pass
