### ISSUE TITLE
Operation: Create HD Wallet

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#65]
- [x] Generate private key
- [x] Generate mnemonic
- [x] Store it in the state

The mnemonic / private key will be used later to backup the wallet

Aha! Link: https://kycc.aha.io/features/MOBILE-48

**Comment by CortecKYC** [comment]
@rhdelima Please test

**Comment by rhdelima** [comment]
Looks good. Pass
