### ISSUE TITLE
Deploy Android APK

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#67]
- [x] Generate github release with apk
- [x] Internal Users should be able to download and install the app

Aha! Link: https://kycc.aha.io/features/MOBILE-46

**Comment by CortecKYC** [comment]
Waiting for Playstore approval

**Comment by maycon-mello** [comment]
We have got the play store approval

**Comment by CortecKYC** [comment]
@maycon-mello What's next? Can we start testing the app in Android?

**Comment by maycon-mello** [comment]
> @maycon-mello What's next? Can we start testing the app on Android?

Yes, this is the link to install the app https://play.google.com/apps/internaltest/4700201663026938761

**Comment by CortecKYC** [comment]
@maycon-mello We need invitations:

![not_invited](https://user-images.githubusercontent.com/47594955/69951866-5f346100-14f6-11ea-99f1-17ca1a97d3ba.png)
