### ISSUE TITLE
Redux: Unlock Wallet

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#69]
* Giver user has created an HD wallet
  * When user enter in the App
    * Then display the unlock wallet screen
  * When user enter the wrong password
    * Then show up an error message
  * When user enter the right password
    * Then redirect the user to the dashboard screen

![image](https://user-images.githubusercontent.com/12645078/66389907-d7235680-e99f-11e9-8ead-1b54660aed74.png)

![image](https://user-images.githubusercontent.com/12645078/66389935-e5717280-e99f-11e9-97d7-541974cac703.png)

Aha! Link: https://kycc.aha.io/features/MOBILE-44

**Comment by rhdelima** [comment]
Looks good. Missing links will be logged on separate ticket.

**Comment by CortecKYC** [comment]
@rhdelima Can I close the ticket?

**Comment by rhdelima** [comment]
@CortecKYC Yes, please.
