### ISSUE TITLE
MOB4: Dashboard Empty State

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#99]
- [x] Create empty state component
- [x] Place in the dashboard when there is nothing to show

Aha! Link: https://kycc.aha.io/features/MOBILE-66

**Comment by rhdelima** [comment]
@maycon-mello Please some issues below:
1. Move `KEY` down on SelfKey widget
2. Should show `$0.00 USD` under `My Tokens`
3. Missing `Empty state message`
![image](https://user-images.githubusercontent.com/10294014/70222241-afc0ee00-1784-11ea-82eb-6a4c267caf0c.png)

**Comment by maycon-mello** [comment]
This is ready for QA.

Can check on this release:
https://play.google.com/apps/test/RQd33H5HZNs/ahAAvZMmjoaaFZkYH7A5OBvlu6xNgxC4FojF6mAGFdJkxzzLZeXmwYSbOaYJ_9WuOVFHzKmX6Ay3YtMVbYYlfoKr7U

**Comment by CortecKYC** [comment]
@maycon-mello Do we need an invitation to test that release you posted above?
When I click on the link I get an error that it doesn't exist.

**Comment by maycon-mello** [comment]
> @maycon-mello Do we need an invitation to test that release you posted above?
> When I click on the link I get an error that it doesn't exist (Item not found. Retry)

It should be public, just need to have the link to access:

https://play.google.com/apps/test/RQd33H5HZNs/ahAAvZMmjoaaFZkYH7A5OBvlu6xNgxC4FojF6mAGFdJkxzzLZeXmwYSbOaYJ_9WuOVFHzKmX6Ay3YtMVbYYlfoKr7U

I'm testing in another devices and it works well, does it works for you @rhdelima?

**Comment by CortecKYC** [comment]
I see two errors:
1. KI as symbol for KEY
2. $NaN USD instead of $0.00 USD

![errors](https://user-images.githubusercontent.com/47594955/70718072-d2f11d80-1cef-11ea-808e-96fc732687b4.jpg)

**Comment by maycon-mello** [comment]
> @maycon-mello I see two errors:
> 
> 1. KI as the symbol for KEY
> 2. $NaN USD instead of $0.00 USD
> 
> ![errors](https://user-images.githubusercontent.com/47594955/70718072-d2f11d80-1cef-11ea-808e-96fc732687b4.jpg)

Thanks, i've fixed these issues

https://play.google.com/apps/internaltest/4700201663026938761

**Comment by rhdelima** [comment]
Looks good now. Pass

![image](https://user-images.githubusercontent.com/10294014/70890879-0fd75000-2021-11ea-928f-9a62fa7c36d0.png)
